apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube1
  template:
    metadata:
      labels:
        app: kube1
    spec:
      containers:
      - name: kube1-container
        image: satyamamrutkar/kube1:latest
        ports:
        - containerPort: 80
